// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvGDSyjRMWPbDO7XYeFz2IJ5dFBRG8zAs',
    appId: '1:682244412177:web:b6c711e79e5b468a73f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    authDomain: 'friendapp-6ff9c.firebaseapp.com',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    measurementId: 'G-9E5Q9MCQL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcexcQgYTUF6znsQkliaNMKweOskbnn0',
    appId: '1:682244412177:android:0d8a7f481a4ee02473f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBckMZhBAYWAJixF3NrvOk1mcW0gJ5KI1U',
    appId: '1:682244412177:ios:ff3c7b3fdc12b32773f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    iosBundleId: 'com.example.lovemsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBckMZhBAYWAJixF3NrvOk1mcW0gJ5KI1U',
    appId: '1:682244412177:ios:a7552361024c7c1273f2b0',
    messagingSenderId: '682244412177',
    projectId: 'friendapp-6ff9c',
    databaseURL: 'https://friendapp-6ff9c-default-rtdb.firebaseio.com',
    storageBucket: 'friendapp-6ff9c.appspot.com',
    iosBundleId: 'com.example.lovemsg.RunnerTests',
  );
}
